files:
  - source: core/i18n/src/main/res/values/strings.xml
    translation: core/i18n/src/main/res/values-%android_code%/strings.xml
    type: android
  - source: core/i18n/src/main/res/values/units.xml
    translation: core/i18n/src/main/res/values-%android_code%/units.xml
    type: android
